services:
  dls-kafka-broker:
    build:
      context: ../
      dockerfile: dls-kafka-broker/docker/Dockerfile
    image: ${IMAGE_NAME}:latest
    container_name: ${CONTAINER_NAME:-dls-kafka-broker-dev-container}
    volumes:
      - ~/.docker/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
    restart: no
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1024M
    tmpfs:
      - /tmp

